package com.test.user.rest;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

public class UserControllerTest {
    @Test
    public void testSomeLibraryMethod() {
        // Dummy
    }
}
